"""empty message

Revision ID: 0593f4af7dff
Revises: 44fb5b2d9a47
Create Date: 2021-04-30 11:20:20.873684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0593f4af7dff'
down_revision = '44fb5b2d9a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('salary')

    # ### end Alembic commands ###
