"""empty message

Revision ID: 40fa293b9fe7
Revises: acda2a349580
Create Date: 2021-04-30 15:05:33.737390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fa293b9fe7'
down_revision = 'acda2a349580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageurl', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('imageurl')

    # ### end Alembic commands ###
